# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Task10_GUI_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 697)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.morphologicalProcessComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.morphologicalProcessComboBox.setGeometry(QtCore.QRect(40, 20, 201, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.morphologicalProcessComboBox.setFont(font)
        self.morphologicalProcessComboBox.setObjectName("morphologicalProcessComboBox")
        self.morphologicalProcessComboBox.addItem("")
        self.morphologicalProcessComboBox.addItem("")
        self.morphologicalProcessComboBox.addItem("")
        self.morphologicalProcessComboBox.addItem("")
        self.morphologicalProcessComboBox.addItem("")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 110, 301, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.originalImageGridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.originalImageGridLayout.setContentsMargins(0, 0, 0, 0)
        self.originalImageGridLayout.setObjectName("originalImageGridLayout")
        self.bestNoiseRemovalImageLabel = QtWidgets.QLabel(self.centralwidget)
        self.bestNoiseRemovalImageLabel.setGeometry(QtCore.QRect(330, 370, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bestNoiseRemovalImageLabel.setFont(font)
        self.bestNoiseRemovalImageLabel.setObjectName("bestNoiseRemovalImageLabel")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(480, 110, 301, 221))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.morphologicalProcessImageGridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.morphologicalProcessImageGridLayout.setContentsMargins(0, 0, 0, 0)
        self.morphologicalProcessImageGridLayout.setObjectName("morphologicalProcessImageGridLayout")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(270, 400, 301, 221))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.bestNoiseRemovalImageGridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.bestNoiseRemovalImageGridLayout.setContentsMargins(0, 0, 0, 0)
        self.bestNoiseRemovalImageGridLayout.setObjectName("bestNoiseRemovalImageGridLayout")
        self.morphologicalProcessImageLabel = QtWidgets.QLabel(self.centralwidget)
        self.morphologicalProcessImageLabel.setGeometry(QtCore.QRect(560, 80, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.morphologicalProcessImageLabel.setFont(font)
        self.morphologicalProcessImageLabel.setText("")
        self.morphologicalProcessImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.morphologicalProcessImageLabel.setObjectName("morphologicalProcessImageLabel")
        self.originalImageLabel = QtWidgets.QLabel(self.centralwidget)
        self.originalImageLabel.setGeometry(QtCore.QRect(160, 80, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.originalImageLabel.setFont(font)
        self.originalImageLabel.setObjectName("originalImageLabel")
        self.bestNoiseRemovalImageText = QtWidgets.QLabel(self.centralwidget)
        self.bestNoiseRemovalImageText.setGeometry(QtCore.QRect(320, 640, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bestNoiseRemovalImageText.setFont(font)
        self.bestNoiseRemovalImageText.setObjectName("bestNoiseRemovalImageText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.morphologicalProcessComboBox.setItemText(0, _translate("MainWindow", "Choose Morphological Process"))
        self.morphologicalProcessComboBox.setItemText(1, _translate("MainWindow", "Erosion"))
        self.morphologicalProcessComboBox.setItemText(2, _translate("MainWindow", "Dilation"))
        self.morphologicalProcessComboBox.setItemText(3, _translate("MainWindow", "Opening"))
        self.morphologicalProcessComboBox.setItemText(4, _translate("MainWindow", "Closing"))
        self.bestNoiseRemovalImageLabel.setText(_translate("MainWindow", "Best Noise Removal"))
        self.originalImageLabel.setText(_translate("MainWindow", "Original Image"))
        self.bestNoiseRemovalImageText.setText(_translate("MainWindow", "Opening Followed by Closing"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
